### ISSUE TITLE
Taking 3rd dimension in account for calculating MSD

### ISSUE THREAD

**Issue by sid6155330** [tinevez/msdanalyzer#5]
Hi @tinevez 

Thanks for sharing the code.  I have 3D data coordinates (x,y,z) for freely diffusing colloidal microspheres. How can I incorporate the 3rd dimension in the example code? (https://tinevez.github.io/msdanalyzer/tutorial/MSDTuto_brownian.html).

I can see the cell `tracks` in the workspace contains x,y,z coordinates along with the time steps when I define `N_DIM=3` .
I believe it has something to do with the `ma.plotTracks`

Thanks

**Comment by tinevez** [comment]
Hello @sid6155330 

You just have to enter the coordinates as a matrix of column: 
`[ T X Y Z ]`
etc
